name: CaSILE
description: The CaSILE toolkit, a book publishing workflow employing SILE and
  other wizardry.
outputs:
  DISTDIR:
    description: Output directory
  PROJECT:
    description: Project name
  VERSION:
    description: Version string
runs:
  using: docker
  image: docker://ghcr.io/sile-typesetter/casile:v0.4.4
  args:
    - make
branding:
  icon: printer
  color: orange
