name: CaSILE
description: The CaSILE toolkit, a book publishing workflow employing SILE and other wizardry.
outputs:
  DISTDIR:
    description: Output directory
  PROJECT:
    description: Project name
  VERSION:
    description: Version string
runs:
  using: docker
  image: Dockerfile
  args:
    - make
branding:
  icon: printer
  color: orange
