[package]
name = "casile"
version = "0.2.0"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2018"
description = "The command line interface to the CaSILE toolkit, a book publishing workflow employing SILE and other wizardry"
homepage = "https://github.com/sile-typesetter/casile"
repository = "https://github.com/sile-typesetter/casile"
license = "AGPL-3"
build = "build.rs"

[dependencies]
# Using Git HEAD because of https://github.com/projectfluent/fluent-rs/issues/175
fluent = { git = "https://github.com/projectfluent/fluent-rs" }
fluent-fallback = { git = "https://github.com/projectfluent/fluent-rs" }
fluent-langneg = "0.12.1"
# fluent-resmgr = { git = "https://github.com/projectfluent/fluent-rs" }
git2 = "0.13.5"
regex = "1.3.7"
rust-embed = "5.5.1"
subprocess = "0.2.4"
unic-langid = "0.8.0"

[dependencies.clap]
# Unrleleased Clap has integrated structopt
git = "https://github.com/clap-rs/clap"
# version = "3.0.0"
features = ["suggestions", "color", "wrap_help", "derive", "std", "cargo", "unstable"]

[build-dependencies]
clap = { git = "https://github.com/clap-rs/clap" }
clap_generate = { git = "https://github.com/clap-rs/clap" }
vergen = "3.1.0"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1.0.4"

[profile.release]
lto = true
