[package]
name = "casile"
version = "0.10.3"
authors = [ "Caleb Maclennan <caleb@alerque.com>" ]
edition = "2018"
description = "The command line interface to the CaSILE toolkit, a book publishing workflow employing SILE and other wizardry"
homepage = "https://github.com/sile-typesetter/casile"
repository = "https://github.com/sile-typesetter/casile"
license = "AGPL-3"
build = "build.rs"

[dependencies]
colored = "2.0.0"
fluent = "0.12.0"
fluent-fallback = "0.0.4"
fluent-langneg = "0.13.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
num_cpus = "1.13.1"
rayon = "1.5.3"
rust-embed = "6.4.0"
subprocess = "0.2.9"
unic-langid = "0.9.0"

  [dependencies.config]
  version = "0.11.0"
  default-features = false
  features = [ "yaml" ]

  [dependencies.clap]
  version = "3.1.18"
  features = [ "derive", "wrap_help" ]

  [dependencies.git2]
  version = "0.14.4"
  default-features = false

  [dependencies.git-warp-time]
  version = "0.4.5"
  default-features = false

  [dependencies.Inflector]
  version = "0.11.4"
  default-features = false

  [dependencies.regex]
  version = "1.5.6"
  default-features = false
  features = [ "std" ]

[build-dependencies]
clap = "3.1.18"
clap_complete = "3.1.4"

  [build-dependencies.vergen]
  version = "7.2.1"
  default-features = false
  features = [ "build", "git" ]

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"

[profile.release]
lto = true
