[package]
name = "casile"
version = "0.2.0"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2018"
description = "The command line interface to the CaSILE toolkit, a book publishing workflow employing SILE and other wizardry"
homepage = "https://github.com/sile-typesetter/casile"
repository = "https://github.com/sile-typesetter/casile"
license = "AGPL-3"
build = "build.rs"

[dependencies]
elsa = "1.3.2"
# Using Git HEAD because of https://github.com/projectfluent/fluent-rs/issues/175
fluent = { git = "https://github.com/projectfluent/fluent-rs" }
fluent-fallback = { git = "https://github.com/projectfluent/fluent-rs" }
fluent-langneg = "0.12.1"
# fluent-resmgr = { git = "https://github.com/projectfluent/fluent-rs" }
git2 = "0.13.5"
regex = "1.3.7"
structopt = "0.3.14"
unic-langid = "0.8.0"

[build-dependencies]
vergen = "3.1.0"

[profile.release]
lto = true
