[package]
name = "casile"
version = "0.2.0"
authors = ["Caleb Maclennan <caleb@alerque.com>"]
edition = "2018"
description = "CLI for the CaSILE toolkit, a book publishing workflow employing SILE and other wizardry"
homepage = "https://github.com/sile-typesetter/casile"
repository = "https://github.com/sile-typesetter/casile"
license = "AGPL-3"
build = "build.rs"

[dependencies]
structopt = "0.3.14"

[build-dependencies]
vergen = "3.1.0"

[profile.release]
lto = true
