name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch Tags
        run: |
          git fetch --prune --tags ||:
      - name: Setup system dependencies
        run: |
          sudo apt-get install autoconf-archive
      - name: Configure
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./bootstrap.sh
          ./configure --without-{bash,fish,zsh}-completion-dir --disable-dependencies
          echo "VERSION=$(./build-aux/git-version-gen .tarball-version)" >> $GITHUB_ENV
          echo "MAKEFLAGS=-j$(nproc) -Otarget" >> $GITHUB_ENV
      - name: Build source package
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          make dist
          echo ISRELEASETAG=$(grep -Pqx '\d+\.\d+\.\d+' .version && echo true || echo false) >> $GITHUB_ENV
      - name: Upload Artifacts
        if: ${{ env.ISRELEASETAG == 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: casile-${{ env.VERSION }}
          path: casile*-${{ env.VERSION }}.zip
      - name: Publish Release
        if: ${{ (env.ISRELEASETAG == 'true' && contains(github.ref, 'refs/tags/v')) }}
        uses: softprops/action-gh-release@v0.1.5
        with:
          body_path: casile-${{ env.VERSION }}.md
          files: |
            casile-${{ env.VERSION }}.zip
            casile-${{ env.VERSION }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.token }}
