name: Rust Test

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo test
        run: |
          cargo test --locked
